// Jöle Atış (ana oyun) bölümleri. Her bölüm, küplerden oluşan bir piksel resimdir.
// Harfler renkleri gösterir (bkz. palette.js), '.' boş hücredir.

import { PALETTE } from '../palette.js';
import { SHAPE_ORDER } from './shapes.js';
import { GENERATED_SHOOTER } from '../generated/shooter.js';

export const CUBE_COLORS = Object.fromEntries(Object.entries(PALETTE).map(([k, v]) => [k, v.base]));

// slots: bekleme kutusu, columns: jöle sütunu, belt: kaykay yolundaki en fazla jöle,
// ammo: mermi parçaları, shuffle: sıralamanın ne kadar karışık olacağı (0 = en kolay),
// abilities: bu bölümde görülebilecek karakterler, abilityRate: bir jölenin karakterli olma olasılığı,
// intro: bu bölümde ilk kez tanıtılan karakter.
// Zorluk değerleri, rastgele oynayan bir botun kazanma oranı bölümden bölüme düşecek şekilde
// simülasyonla ayarlandı (bkz. tests/shooter.test.js — her bölüm akıllı bir oyuncuyla kazanılabilir).
// 8. ve 10. bölümler bilerek daha kolay: zor bölümlerin arasında "nefes bölümü".
// Engel katmanı: verilen karakterdeki hücreler (renk harfi) zırhlı ('a') ya da kilitli ('l') olur
function marks(art, rules) {
  return art.map((row, y) => [...row].map((ch, x) => rules(ch, x, y) ?? '.').join(''));
}

const ROKET = [
  '.....r.....',
  '....rrr....',
  '...rwwwr...',
  '...wwbww...',
  '...wbbbw...',
  '...wwbww...',
  '...wwwww...',
  '..rwwwwwr..',
  '.rrwwwwwrr.',
  'rr.ooooo.rr',
  '...o.y.o...',
  '....yyy....',
];

const DONDURMA = [
  '...iiiii...',
  '..iiiiiii..',
  '.iieiiieii.',
  '.iiiiiiiii.',
  '.ccccccccc.',
  '.cmcccccmc.',
  '..nnnnnnn..',
  '..ntntntn..',
  '...nnnnn...',
  '...ntntn...',
  '....nnn....',
  '.....n.....',
];

const KAPLUMBAGA = [
  '....nnnnn....',
  '...nomomon...',
  '..nmnnnnnmn..',
  '.nmnnoooonmn.',
  '.nnmnnnnnmnn.',
  'lgnmnnoonnmgl',
  'l.ggggggggg.l',
  '..g.g...g.g..',
  '...........ll',
];

const FENER = [
  '....yyy....',
  '...kkkkk...',
  '...kyyyk...',
  '...kkkkk...',
  '....rrr....',
  '....www....',
  '....rrr....',
  '...wwwww...',
  '...rrrrr...',
  '...wwwww...',
  '..rrrrrrr..',
  'bbbbbbbbbbb',
  'bcbbcbbbcbb',
];

const GOKKUSAGI = [
  '...rrrrrrr...',
  '..rooooooor..',
  '.royyyyyyyor.',
  'roygggggggyor',
  'roygbbbbbgyor',
  'roygb...bgyor',
  'roygb...bgyor',
  'wwwww...wwwww',
  '.www.....www.',
];

const RAW_LEVELS = [
  {
    id: 1, name: 'Kalp', slots: 5, columns: 2, belt: 4, ammo: [10, 20], shuffle: 0,
    art: [
      '.rr...rr.',
      'rwrr.rrrr',
      'rwrrrrrrr',
      'rrrrrrrrr',
      '.rrrrrrr.',
      '..rrrrr..',
      '...rrr...',
      '....r....',
    ],
  },
  {
    id: 2, name: 'Mantar', slots: 5, columns: 2, belt: 4, ammo: [10, 20], shuffle: 0,
    art: [
      '...rrrr...',
      '..rrwwrr..',
      '.rrwwrrrr.',
      'rrrrrrwwrr',
      'rwwrrrwwrr',
      'rrrrrrrrrr',
      '...wwww...',
      '...wkwk...',
      '...wwww...',
      '....ww....',
    ],
  },
  {
    id: 3, name: 'Çiçek', slots: 4, columns: 3, belt: 4, ammo: [10, 20], shuffle: 0,
    abilities: ['bounce'], abilityRate: 0.35, intro: 'bounce',
    art: [
      '...iiii...',
      '..iiiiii..',
      '.iiyyyyii.',
      '.iiyooyii.',
      '.iiyyyyii.',
      '..iiiiii..',
      '...iiii...',
      '....gg....',
      '.gg.gg.gg.',
      '..gggggg..',
      '....gg....',
    ],
  },
  {
    id: 4, name: 'Dondurma', slots: 3, columns: 3, belt: 5, ammo: [10, 20], shuffle: 3,
    abilities: ['bounce'], abilityRate: 0.25,
    art: [
      '....rr....',
      '...iiii...',
      '..iiwiii..',
      '.iiiiiiii.',
      '.mmmmwmmm.',
      '.mmmmmmmm.',
      '..nnnnnn..',
      '..nynnyn..',
      '...nnnn...',
      '...nynn...',
      '....nn....',
      '....n.....',
    ],
  },
  {
    id: 5, name: 'Kedi', slots: 3, columns: 3, belt: 4, ammo: [10, 20], shuffle: 6,
    abilities: ['bounce'], abilityRate: 0.25,
    art: [
      '.o.......o.',
      '.oo.....oo.',
      '.ooooooooo.',
      'ooooooooooo',
      'oogkooogkoo',
      'ooooooooooo',
      'owwooioowwo',
      'owwwwwwwwwo',
      '.owwwwwwwo.',
      '..ooooooo..',
    ],
  },
  {
    id: 6, name: 'Yıldız', slots: 2, columns: 4, belt: 3, ammo: [5, 10, 20], shuffle: 3,
    abilities: ['bounce', 'fast'], abilityRate: 0.3, intro: 'fast',
    art: [
      '.....o.....',
      '....oyo....',
      '....oyo....',
      '...oyyyo...',
      'ooooyyyoooo',
      'oyyyyyyyyyo',
      '.oyykyykyo.',
      '..oyyyyyo..',
      '..oyyiyyo..',
      '.oyyyoyyyo.',
      '.oyyo.oyyo.',
      'oooo...oooo',
    ],
  },
  {
    id: 7, name: 'Ev', slots: 3, columns: 3, belt: 3, ammo: [10, 20], shuffle: 9,
    abilities: ['bounce', 'fast'], abilityRate: 0.25,
    art: [
      '.....rr.....',
      '....rrrr....',
      '...rrrrrr.k.',
      '..rrrrrrrrk.',
      '.rrrrrrrrrr.',
      'rrrrrrrrrrrr',
      '.yyyyyyyyyy.',
      '.ybbyyyybby.',
      '.ybbyyyybby.',
      '.yyyynnyyyy.',
      '.yyyynnyyyy.',
      '.yyyynnyyyy.',
      'gggggggggggg',
    ],
  },
  {
    id: 8, name: 'Çilek', slots: 3, columns: 3, belt: 3, ammo: [10, 20], shuffle: 0,
    abilities: ['bounce', 'fast'], abilityRate: 0.25,
    art: [
      '...g.g.g...',
      '....ggg....',
      '..rrrgrrr..',
      '.rrrrrrrrr.',
      'rryrrryrrry',
      'rrrrrrrrrrr',
      '.rryrrryrr.',
      '.rrrrrrrrr.',
      '..rryrrrr..',
      '...rrrrr...',
      '....rrr....',
      '.....r.....',
    ],
  },
  {
    id: 9, name: 'Gökkuşağı', slots: 3, columns: 4, belt: 3, ammo: [10, 20], shuffle: 0,
    abilities: ['bounce', 'fast'], abilityRate: 0.2,
    art: [
      '....rrrrr....',
      '..rroooooorr.',
      '.rooyyyyyyoor',
      'roygggggggyor',
      'roygbbbbbgyor',
      'roygbpppbgyor',
      'roygbp.pbgyor',
      'roygbp.pbgyor',
      'ww.........ww',
      'www.......www',
    ],
  },
  {
    id: 10, name: 'Balık', slots: 2, columns: 4, belt: 3, ammo: [5, 10, 20], shuffle: 3,
    abilities: ['bounce', 'fast', 'pierce'], abilityRate: 0.3, intro: 'pierce',
    art: [
      '.....bbbb....',
      '...bbbbbbb...',
      '.bbbbbbbbbbo.',
      'bbwkbbbbbbboo',
      'bbwwbbbbbbooo',
      'bbbbbbbbbbboo',
      '.bbbbbbbbbbo.',
      '..bbbbbbbb...',
      '....ooo......',
      '.....oo......',
    ],
  },
  {
    id: 11, name: 'Karpuz', slots: 1, columns: 4, belt: 3, ammo: [5, 10], shuffle: 0,
    abilities: ['bounce', 'fast', 'pierce'], abilityRate: 0.25,
    art: [
      'rrkrrrrkrrrkr',
      'rrrrrkrrrrrrr',
      '.rrkrrrrrkrr.',
      '.rrrrrrrrrrr.',
      '..wrrrkrrrw..',
      '..gwwwwwwwg..',
      '...ggggggg...',
      '....ggggg....',
    ],
  },
  {
    id: 12, name: 'Roket', slots: 1, columns: 3, belt: 3, ammo: [5, 10, 20], shuffle: 3,
    abilities: ['bounce', 'fast', 'pierce'], abilityRate: 0.25,
    art: [
      '.....rr.....',
      '....rrrr....',
      '...rrrrrr...',
      '...wwwwww...',
      '...wwbbww...',
      '...wbbbbw...',
      '...wwbbww...',
      '...wwwwww...',
      '...wwwwww...',
      '..rwwwwwwr..',
      '.rrwwwwwwrr.',
      'rrrwwwwwwrrr',
      '...oyyyyo...',
      '....oyyo....',
      '.....oo.....',
    ],
  },
  {
    id: 13, name: 'Ayıcık', slots: 1, columns: 3, belt: 4, ammo: [10, 20], shuffle: 3,
    abilities: ['bounce', 'fast', 'pierce'], abilityRate: 0.25,
    art: [
      '.nn......nn.',
      'nnnn....nnnn',
      'nnnnnnnnnnnn',
      '.nnnnnnnnnn.',
      '.nnknnnnknn.',
      '.nnnnnnnnnn.',
      '.nnnwwwwnnn.',
      '.nnwwkkwwnn.',
      '.tnwwwwwwnt.',
      '..nnnwwnnn..',
      '...nnnnnn...',
    ],
  },
  {
    id: 14, name: 'Kaktüs', slots: 1, columns: 3, belt: 3, ammo: [10, 20], shuffle: 9,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.3, intro: 'bomb',
    art: [
      '.....y.....',
      '....yiy....',
      '.....g.....',
      '....ggg....',
      '.g..ggg....',
      '.g..ggg..g.',
      '.gg.gwg..g.',
      '..gggggggg.',
      '....ggg.gg.',
      '....gwg....',
      '....ggg....',
      '.ooooooooo.',
      '..ononono..',
      '..ooooooo..',
    ],
  },
  {
    id: 15, name: 'Ahtapot', slots: 1, columns: 4, belt: 3, ammo: [5, 10], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.25,
    art: [
      '....iiiii....',
      '..iiiiiiiii..',
      '.iiiiiiiiiii.',
      '.iwwiiiiiwwi.',
      '.iwkiiiiikwi.',
      '.iiiiiiiiiii.',
      '.iiiirrriiii.',
      '..iiiiiiiii..',
      '.ii.ii.ii.ii.',
      'ii..ii.ii..ii',
      'i...i...i...i',
    ],
  },
  {
    id: 16, name: 'Kek', slots: 2, columns: 3, belt: 3, ammo: [5, 10, 20], shuffle: 0,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.25,
    art: [
      '.....rr.....',
      '.....rr.....',
      '...iiiiii...',
      '..iiyiibii..',
      '.iiiiiiiiii.',
      '.ibiiyiiiyi.',
      'iiiiiiiiiiii',
      '.oonoonoono.',
      '.oonoonoono.',
      '..onoonoon..',
      '..onoonoon..',
      '...oooooo...',
    ],
  },
  {
    id: 17, name: 'Kurbağa', slots: 1, columns: 4, belt: 3, ammo: [5, 10], shuffle: 9,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.25,
    art: [
      '.www.....www.',
      'wwkwwgggwwkww',
      'wwwwwgggwwwww',
      'ggggggggggggg',
      'gtgggggggggtg',
      'ggrrrrrrrrrgg',
      'gggrrrrrrrggg',
      'ggggggggggggg',
      '.ggggggggggg.',
      '.gg.ggggg.gg.',
      'gggg.....gggg',
    ],
  },
  {
    id: 18, name: 'Kelebek', slots: 1, columns: 3, belt: 4, ammo: [5, 10], shuffle: 9,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: [
      'pp....k....pp',
      'pppp..k..pppp',
      'ppeepkkkpeepp',
      'pppeepkpeeppp',
      'ppppppkpppppp',
      '.ppppbkbpppp.',
      '..ebbbkbbbe..',
      '.bbybbkbbybb.',
      '.bbbbbkbbbbb.',
      '..bbb.k.bbb..',
      '......k......',
    ],
  },
  {
    id: 19, name: 'Penguen', slots: 2, columns: 4, belt: 3, ammo: [5, 10, 20], shuffle: 9,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: [
      '...kkkkk...',
      '..kkkkkkk..',
      '.kkwkkkwkk.',
      '.kwwwkwwwk.',
      '.kwwwowwwk.',
      'kkwwwwwwwkk',
      'kkwwwwwwwkk',
      'kwwwwwwwwwk',
      'kwwwwwwwwwk',
      '.kwwwwwwwk.',
      '..kkkkkkk..',
      '..oo...oo..',
    ],
  },
  {
    id: 20, name: 'Taç', slots: 1, columns: 4, belt: 4, ammo: [5, 10, 20], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: [
      'y.....y.....y',
      'yy...yyy...yy',
      'yyy.yyyyy.yyy',
      'yyyyyyyyyyyyy',
      'yyryyybyyygyy',
      'yyyyyyyyyyyyy',
      'ooooooooooooo',
      'oyoyoyoyoyoyo',
      'ooooooooooooo',
    ],
  },
  // ---- 21–25: zırhlı ve kilitli küplerle son bölümler ----
  {
    id: 21, name: 'Kaplumbağa', slots: 1, columns: 5, belt: 3, ammo: [5, 5, 10], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: KAPLUMBAGA,
    mods: marks(KAPLUMBAGA, (ch, x, y) => (ch === 'o' ? 'a' : ch === 'm' && y % 2 === 0 ? 'l' : null)),
  },
  {
    id: 22, name: 'Roket', slots: 1, columns: 4, belt: 3, ammo: [5, 10], shuffle: 9,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: ROKET,
    mods: marks(ROKET, (ch) => (ch === 'b' ? 'a' : ch === 'y' ? 'l' : null)),
  },
  {
    id: 23, name: 'Dondurma', slots: 2, columns: 5, belt: 4, ammo: [5, 10, 20], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: DONDURMA,
    mods: marks(DONDURMA, (ch, x, y) => (ch === 'e' || ch === 'm' ? 'a' : ch === 't' ? 'l' : null)),
  },
  {
    id: 24, name: 'Deniz Feneri', slots: 1, columns: 5, belt: 4, ammo: [5, 10, 20], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: FENER,
    mods: marks(FENER, (ch, x, y) => (ch === 'r' ? 'a' : ch === 'y' && y > 0 ? 'l' : null)),
  },
  {
    id: 25, name: 'Gökkuşağı', slots: 2, columns: 4, belt: 3, ammo: [5, 10, 20], shuffle: 6,
    abilities: ['bounce', 'fast', 'pierce', 'bomb'], abilityRate: 0.2,
    art: GOKKUSAGI,
    mods: marks(GOKKUSAGI, (ch, x, y) => (ch === 'g' || ch === 'o' ? 'a' : ch === 'b' && y > 3 ? 'l' : null)),
  },
];

// Her bölümün jöle şekli sırayla döner: ayıcık, kalp, kola şişesi, yıldız, halka, çilek
// El yapımı bölümlerin ardından ajanın planladığı bölümler gelir (bkz. level-agent)
export const MAIN_LEVELS = [...RAW_LEVELS, ...GENERATED_SHOOTER].map((l) => ({
  abilities: [],
  abilityRate: 0,
  intro: null,
  ...l,
  shape: SHAPE_ORDER[(l.id - 1) % SHAPE_ORDER.length],
}));

export const getMainLevel = (id) => MAIN_LEVELS.find((l) => l.id === id) ?? null;
