// Nakış bölümleri: renksiz tabloyu iplerle içten dışa doğru işle.
// Harfler renkleri gösterir (bkz. palette.js), '.' tablonun dışıdır (ip oradan geçebilir).
//
// spool: her makaradaki ip uzunluğu (hepsi aynı), slots: bekleme kutusu, columns: makara sütunu,
// belt: yoldaki en fazla makara, shuffle: makara sırasının ne kadar karışık olduğu (0 = en kolay),
// slack: en içteki katmanın kaç katman dışına kadar işlenebileceği.
// Değerler simülasyonla ayarlandı: rastgele oynayan birinin kazanma oranı %100'den %38'e iner.

export const NAKIS_LEVELS = [
  {
    id: 1, name: 'Kalp', spool: 6, slots: 5, columns: 2, belt: 3, shuffle: 0, slack: 1,
    tip: 'Önce içteki pembeyi işle: kırmızı çerçeve kapanırsa pembeye yol kalmaz!',
    art: [
      '.rr...rr.',
      'riir.riir',
      'riiiriiir',
      'riiiiiiir',
      '.riiiiir.',
      '..riiir..',
      '...rir...',
      '....r....',
    ],
  },
  {
    id: 2, name: 'Hedef', spool: 6, slots: 5, columns: 2, belt: 3, shuffle: 2, slack: 1,
    tip: 'Halkaları merkezden dışa doğru işle.',
    art: [
      'rrrrrrrrr',
      'rwwwwwwwr',
      'rwbbbbbwr',
      'rwbyyybwr',
      'rwbyoybwr',
      'rwbyyybwr',
      'rwbbbbbwr',
      'rwwwwwwwr',
      'rrrrrrrrr',
    ],
  },
  {
    id: 3, name: 'Çiçek', spool: 6, slots: 4, columns: 3, belt: 4, shuffle: 2, slack: 1,
    art: [
      '...iiii...',
      '..iiiiii..',
      '.iiyyyyii.',
      '.iiyooyii.',
      '.iiyooyii.',
      '.iiyyyyii.',
      '..iiiiii..',
      '...iiii...',
      '....gg....',
      '....gg....',
    ],
  },
  {
    id: 4, name: 'Güneş', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1,
    art: [
      'y....y....y',
      '.y..yyy..y.',
      '..yyyyyyy..',
      '.yyoooooyy.',
      'yyoorrrooyy',
      '.yyoooooyy.',
      '..yyyyyyy..',
      '.y..yyy..y.',
      'y....y....y',
    ],
  },
  {
    id: 5, name: 'Ev', spool: 8, slots: 3, columns: 3, belt: 4, shuffle: 4, slack: 1,
    art: [
      '.....rr.....',
      '....rrrr....',
      '...rrrrrr...',
      '..rrrrrrrr..',
      '.rrrrrrrrrr.',
      'rrrrrrrrrrrr',
      '.wwwwwwwwww.',
      '.wbbwwwwbbw.',
      '.wbbwnnwbbw.',
      '.wwwwnnwwww.',
      '.wwwwnnwwww.',
    ],
  },
  {
    id: 6, name: 'Gökkuşağı', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 2, slack: 1,
    art: [
      '...rrrrrrr...',
      '.rrooooooorr.',
      'rrooyyyyyoorr',
      'rooyygggyyoor',
      'royygbbbgyyor',
      'roygbbpbbgyor',
      'roygbp.pbgyor',
      'roygbp.pbgyor',
    ],
  },
  {
    id: 7, name: 'Deniz Feneri', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 2,
    art: [
      'cccccyyccccc',
      'ccccyyyycccc',
      'cccccrrccccc',
      'ccccrwwrcccc',
      'ccccryyrcccc',
      'ccccrrrrcccc',
      'cccccwwccccc',
      'cccccrrccccc',
      'cccccwwccccc',
      'cccccrrccccc',
      'ccccnwwncccc',
      'cccnnrrnnccc',
      'bbnnnnnnnnbb',
      'bbbbbbbbbbbb',
    ],
  },
  {
    id: 8, name: 'Ayçiçekleri', spool: 6, slots: 4, columns: 3, belt: 4, shuffle: 4, slack: 1,
    art: [
      'cyyyccccyyyc',
      'yynyyccyynyy',
      'yynnyccynnyy',
      'cyyycyyycyyc',
      'ccgccynnyccc',
      'ccgcgyyyyccc',
      'cccggcgccccc',
      'ccoooooooocc',
      'ccoyyyyyyocc',
      'ccoooooooocc',
      'cccooooooccc',
      'nnnnnnnnnnnn',
    ],
  },
  {
    id: 9, name: 'Büyük Dalga', spool: 6, slots: 4, columns: 4, belt: 3, shuffle: 4, slack: 1,
    art: [
      'cccccccccccccc',
      'ccddddcccccccc',
      'cdbbbbdccccccc',
      'dbbwwbbdcccccc',
      'dbwccwbbdccwcc',
      'dbwcccwbbdcwwc',
      'dbbwccwbbbdwwb',
      'ddbbwwbbbbbbbb',
      'dddbbbbbbwwbbb',
      'dddddddddddddd',
    ],
  },
  {
    id: 10, name: 'Yıldızlı Gece', spool: 6, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1,
    art: [
      'ddddccccddddyyyd',
      'dyddcwwccdddyoyd',
      'dkdcwddwcddddyyd',
      'dkdcwddwccdyddcd',
      'kkddcwwccddddccd',
      'kkdddcccdydddcwc',
      'kkkddddddddcccwc',
      'kkkbbddddddccwwc',
      'kkbbbbbbddbbbbcc',
      'kknbbnnbbbbnnbbb',
      'kknynnnbnnynnbnb',
      'kknnnnnnnnnnnnnn',
    ],
  },
];

export const getNakisLevel = (id) => NAKIS_LEVELS.find((l) => l.id === id) ?? null;
