// Nakış bölümleri: renksiz tabloyu iplerle içten dışa doğru işle.
// Harfler renkleri gösterir (bkz. palette.js), '.' tablonun dışıdır (ip oradan geçebilir).
//
// spool: her makaradaki ip uzunluğu (hepsi aynı), slots: bekleme kutusu, columns: makara sütunu,
// belt: yoldaki en fazla makara, shuffle: makara sırasının ne kadar karışık olduğu (0 = en kolay),
// slack: en içteki katmanın kaç katman dışına kadar işlenebileceği,
// seed: makara diziliminin tohumu (bölüm numarası değişse de ayarlanan dizilim korunur).
// Değerler simülasyonla ayarlandı: rastgele oynayan birinin kazanma oranı %100'den %38'e iner.

import { MAIN_LEVELS } from '../shooter/levels.js';

export const NAKIS_LEVELS = [
  {
    id: 1, name: 'Kalp', spool: 6, slots: 5, columns: 2, belt: 3, shuffle: 0, slack: 1,
    tip: 'Önce içteki pembeyi işle: kırmızı çerçeve kapanırsa pembeye yol kalmaz!',
    art: [
      '.rr...rr.',
      'riir.riir',
      'riiiriiir',
      'riiiiiiir',
      '.riiiiir.',
      '..riiir..',
      '...rir...',
      '....r....',
    ],
  },
  {
    id: 2, name: 'Hedef', spool: 6, slots: 5, columns: 2, belt: 3, shuffle: 2, slack: 1,
    tip: 'Halkaları merkezden dışa doğru işle.',
    art: [
      'rrrrrrrrr',
      'rwwwwwwwr',
      'rwbbbbbwr',
      'rwbyyybwr',
      'rwbyoybwr',
      'rwbyyybwr',
      'rwbbbbbwr',
      'rwwwwwwwr',
      'rrrrrrrrr',
    ],
  },
  {
    id: 3, name: 'Çiçek', spool: 6, slots: 4, columns: 3, belt: 4, shuffle: 2, slack: 1,
    art: [
      '...iiii...',
      '..iiiiii..',
      '.iiyyyyii.',
      '.iiyooyii.',
      '.iiyooyii.',
      '.iiyyyyii.',
      '..iiiiii..',
      '...iiii...',
      '....gg....',
      '....gg....',
    ],
  },
  {
    id: 4, name: 'Güneş', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1,
    art: [
      'y....y....y',
      '.y..yyy..y.',
      '..yyyyyyy..',
      '.yyoooooyy.',
      'yyoorrrooyy',
      '.yyoooooyy.',
      '..yyyyyyy..',
      '.y..yyy..y.',
      'y....y....y',
    ],
  },
  {
    id: 5, name: 'Ev', spool: 8, slots: 3, columns: 3, belt: 4, shuffle: 4, slack: 1,
    art: [
      '.....rr.....',
      '....rrrr....',
      '...rrrrrr...',
      '..rrrrrrrr..',
      '.rrrrrrrrrr.',
      'rrrrrrrrrrrr',
      '.wwwwwwwwww.',
      '.wbbwwwwbbw.',
      '.wbbwnnwbbw.',
      '.wwwwnnwwww.',
      '.wwwwnnwwww.',
    ],
  },
  {
    id: 6, name: 'Gökkuşağı', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 2, slack: 1,
    art: [
      '...rrrrrrr...',
      '.rrooooooorr.',
      'rrooyyyyyoorr',
      'rooyygggyyoor',
      'royygbbbgyyor',
      'roygbbpbbgyor',
      'roygbp.pbgyor',
      'roygbp.pbgyor',
    ],
  },
  {
    id: 7, name: 'Deniz Feneri', spool: 8, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 2,
    art: [
      'cccccyyccccc',
      'ccccyyyycccc',
      'cccccrrccccc',
      'ccccrwwrcccc',
      'ccccryyrcccc',
      'ccccrrrrcccc',
      'cccccwwccccc',
      'cccccrrccccc',
      'cccccwwccccc',
      'cccccrrccccc',
      'ccccnwwncccc',
      'cccnnrrnnccc',
      'bbnnnnnnnnbb',
      'bbbbbbbbbbbb',
    ],
  },
  {
    id: 8, name: 'Ayçiçekleri', spool: 6, slots: 4, columns: 3, belt: 4, shuffle: 4, slack: 1,
    art: [
      'cyyyccccyyyc',
      'yynyyccyynyy',
      'yynnyccynnyy',
      'cyyycyyycyyc',
      'ccgccynnyccc',
      'ccgcgyyyyccc',
      'cccggcgccccc',
      'ccoooooooocc',
      'ccoyyyyyyocc',
      'ccoooooooocc',
      'cccooooooccc',
      'nnnnnnnnnnnn',
    ],
  },
  {
    id: 9, name: 'Büyük Dalga', spool: 6, slots: 4, columns: 4, belt: 3, shuffle: 4, slack: 1,
    art: [
      'cccccccccccccc',
      'ccddddcccccccc',
      'cdbbbbdccccccc',
      'dbbwwbbdcccccc',
      'dbwccwbbdccwcc',
      'dbwcccwbbdcwwc',
      'dbbwccwbbbdwwb',
      'ddbbwwbbbbbbbb',
      'dddbbbbbbwwbbb',
      'dddddddddddddd',
    ],
  },
  {
    id: 10, name: 'Yıldızlı Gece', spool: 6, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1,
    art: [
      'ddddccccddddyyyd',
      'dyddcwwccdddyoyd',
      'dkdcwddwcddddyyd',
      'dkdcwddwccdyddcd',
      'kkddcwwccddddccd',
      'kkdddcccdydddcwc',
      'kkkddddddddcccwc',
      'kkkbbddddddccwwc',
      'kkbbbbbbddbbbbcc',
      'kknbbnnbbbbnnbbb',
      'kknynnnbnnynnbnb',
      'kknnnnnnnnnnnnnn',
    ],
  },
  // 11–24: yeni tablolar (bazı resimler Jöle Atış'tan), ölçülen zorluğa göre kolaydan zora
  { id: 11, name: 'Kaktüs', spool: 6, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1, seed: 'nakis-23', art: artOf('Kaktüs') },
  { id: 12, name: 'Mantar', spool: 6, slots: 3, columns: 3, belt: 3, shuffle: 4, slack: 1, seed: 'nakis-11', art: artOf('Mantar') },
  { id: 13, name: 'Roket', spool: 6, slots: 3, columns: 4, belt: 4, shuffle: 0, slack: 1, seed: 'nakis-22', art: artOf('Roket') },
  { id: 14, name: 'Balık', spool: 8, slots: 3, columns: 4, belt: 3, shuffle: 4, slack: 1, seed: 'nakis-15', art: artOf('Balık') },
  { id: 15, name: 'Karpuz', spool: 8, slots: 3, columns: 3, belt: 3, shuffle: 4, slack: 1, seed: 'nakis-16', art: artOf('Karpuz') },
  {
    id: 16, name: 'Nazar Boncuğu', spool: 6, slots: 4, columns: 3, belt: 3, shuffle: 0, slack: 1, seed: 'nakis-12',
    art: [
      '...ddddd...',
      '..ddddddd..',
      '.ddwwwwwdd.',
      'ddwwcccwwdd',
      'ddwcckccwdd',
      'ddwckkkcwdd',
      'ddwcckccwdd',
      'ddwwcccwwdd',
      '.ddwwwwwdd.',
      '..ddddddd..',
      '...ddddd...',
    ],
  },
  { id: 17, name: 'Kedi', spool: 8, slots: 3, columns: 3, belt: 3, shuffle: 0, slack: 1, seed: 'nakis-13', art: artOf('Kedi') },
  {
    id: 18, name: 'Lale', spool: 6, slots: 3, columns: 3, belt: 3, shuffle: 4, slack: 2, seed: 'nakis-14',
    art: [
      '..r..r..r..',
      '..rr.r.rr..',
      '..rrrrrrr..',
      '..rrirrir..',
      '..rrrirrr..',
      '...rrrrr...',
      '....rrr....',
      '.....g.....',
      '.g...g...g.',
      '.gg..g..gg.',
      '..gg.g.gg..',
      '...ggggg...',
      '....ggg....',
      '.....g.....',
    ],
  },
  { id: 19, name: 'Kek', spool: 8, slots: 4, columns: 4, belt: 3, shuffle: 0, slack: 1, seed: 'nakis-17', art: artOf('Kek') },
  { id: 20, name: 'Kelebek', spool: 8, slots: 4, columns: 4, belt: 3, shuffle: 4, slack: 1, seed: 'nakis-18', art: artOf('Kelebek') },
  {
    id: 21, name: 'Kız Kulesi', spool: 8, slots: 4, columns: 3, belt: 4, shuffle: 2, slack: 1, seed: 'nakis-19',
    art: [
      'oooooooooooooo',
      'ooooooroooyooo',
      'yyyyyrrryyyyyy',
      'yyyyywwwyyyyyy',
      'yyyyywkwyyyyyy',
      'cccccwwwcccccc',
      'ccccrwwwrccccc',
      'ccccwwkwwccccc',
      'ccccwwwwwccccc',
      'cccnnwwwnnnccc',
      'bbnnnnnnnnnnbb',
      'bbbbnnnnnnbbbb',
      'bbwbbbbbbbbwbb',
      'bbbbbbwbbbbbbb',
    ],
  },
  { id: 22, name: 'Ahtapot', spool: 8, slots: 3, columns: 4, belt: 4, shuffle: 4, slack: 1, seed: 'nakis-21', art: artOf('Ahtapot') },
  { id: 23, name: 'Penguen', spool: 8, slots: 3, columns: 3, belt: 3, shuffle: 4, slack: 1, seed: 'nakis-20', art: artOf('Penguen') },
  {
    id: 24, name: 'Çığlık', spool: 8, slots: 4, columns: 3, belt: 4, shuffle: 0, slack: 1, seed: 'nakis-24',
    art: [
      'oorrroooorrroo',
      'rroooyyyooorrr',
      'ooyyyoooyyyooo',
      'bbboooyyooobbb',
      'bbbbbbooobbbbd',
      'nbbbbbbbbbbbdd',
      'nnbbbbwwwbbddd',
      'nnnbbwkwkwbddd',
      'nnnnbwwkwwbddd',
      'nnnnnbwwwbdddd',
      'nnnnnnkkkddddd',
      'nnnnnkkkkkdddd',
      'nnnnnkkkkkdddd',
      'nnnnnnkkkndddd',
    ],
  },
];

function artOf(name) {
  const level = MAIN_LEVELS.find((l) => l.name === name);
  if (!level) throw new Error(`Jöle Atış'ta '${name}' resmi yok`);
  return level.art;
}

export const getNakisLevel = (id) => NAKIS_LEVELS.find((l) => l.id === id) ?? null;
